sudo: required  # http://docs.travis-ci.com/user/migrating-from-legacy/

services:
  - mysql
 
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  
language: python

python:
  - 3.6
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('ko') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;create database datapeace; use datapeace;"
  - sudo mysql_upgrade -u root --password=ko
  - sudo service mysql restart
  
install: 
  - pip install -r requirements.txt

script:
  - python test.py
